export const allProducts = [
    {
      number: 1,
      name: "Ariana Grande - Sweetener",
      price: 29.99,
      location: "./images/ariana-grande.jpg",
    },
    {
      number: 2,
      name: "Carolina Polachek - Pang",
      price: 29.99,
      location: "./images/caroline-polachek.jpg",
    },
    {
      number: 3,
      name: "Frank Ocean - Blonde",
      price: 29.99,
      location: "./images/frank-ocean.jpg",
    },
    {
      number: 4,
      name: "Harry Styles - Fine Line",
      price: 29.99,
      location: "./images/harry-styles.jpg",
    },
    {
      number: 5,
      name: "Japanese Breakfast - Jubilee",
      price: 29.99,
      location: "./images/japanese-breakfast.jpg",
    },
    {
      number: 6,
      name: "Lorde - Melodrama",
      price: 29.99,
      location: "./images/lorde.jpg",
    },
    {
      number: 7,
      name: "Mac Miller - The Divine Feminine",
      price: 29.99,
      location: "./images/mac-miller.jpg",
    },
    {
      number: 8,
      name: "Pheobe Bridgers - Punisher",
      price: 29.99,
      location: "./images/phoebe-bridgers.jpg",
    },
    {
      number: 9,
      name: "Rihanna - ANTI",
      price: 29.99,
      location: "./images/rihanna.jpg",
    },
    {
      number: 10,
      name: "Tame Impala - Currents",
      price: 29.99,
      location: "./images/tame-impala.jpg",
    },
    {
      number: 11,
      name: "Taylor Swift - Folklore",
      price: 29.99,
      location: "./images/taylor-swift.jpg",
    },
    {
      number: 12,
      name: "Tyler, The Creator - Flower Boy",
      price: 29.99,
      location: "./images/tyler-the-creator.jpg",
    },
    {
      number: 4,
      name: "Harry Styles - Fine Line",
      price: 29.99,
      location: "./images/harry-styles.jpg",
    },
  ];